### ISSUE TITLE
Argon fails to connect after recent vsc update

### ISSUE THREAD

**Issue by henri14871** [argon-rbx/argon-legacy#3]
pls fix ty

**Comment by DervexDev** [comment]
Moved to [argon-legacy](https://github.com/argon-rbx/argon-legacy) as this the repo of the Argon version you are referring to. Related to [this post](https://devforum.roblox.com/t/argon-vs-code-sync-plugin/2021776/570).

I can't exactly reproduce this issue because Argon connects fine for me, but I can see that the code isn't syncing at all. Looks like the last VSC update broke this. I'll fix it tomorrow when I get home.

**Comment by henri14871** [comment]
ok thanks just downgraded my vsc for now so it works fine

**Comment by DervexDev** [comment]
Working on a fix right now and you were right. On Windows you can't even connect to the VSC extension (I previously tested it on macOS).

**Comment by DervexDev** [comment]
Fixed in [1.3.1](https://github.com/argon-rbx/argon-legacy/releases/tag/1.3.1).
